### PR TITLE
Create first Microverse project

### PR DESCRIPTION
**Pull request by Estherstarr**
Set up a "Hello Microverse Project"
-Add the .github/workflow folder
-Add the linters file (.hintrc and .stylelintrc)
-Add the .gitignore file
-Add the README file
-Create index.html and use the h1 tag to write "Hello Microverse"
- Style the project using the style.css file

### CODE REVIEW

**Review by micheaol — CHANGES_REQUESTED** [review]
Hi @Estherstarr , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 

## Required Changes ♻️

- Please ensure that you add test.md file with the text and "this file should be added to gitignore"

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by Estherstarr** [comment]
Required changes made :
-Add test.md in the .gitignore file

**Comment by Estherstarr** [comment]
@micheaol Thank you for the review. I added the required changes

**Comment by micheaol** [comment]
@Estherstarr , Thank you for making the changes as requested. Please submit for re-review on your dashboard.

**Review by Kingstalux — APPROVED** [review]
Hi @Estherstarr , 
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

Good job implementing the required changes 👍  Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
